version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: quiz-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - banco-dados:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - quiz-net
  app:
    container_name: app
    restart: on-failure
    build: .
    working_dir: /app
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - quiz-net
networks:
  quiz-net:
    driver: bridge
volumes:
  banco-dados: